### ISSUE TITLE
`AttributeError: 'BinaryReader' object has no attribute 'tell'`

### ISSUE THREAD

**Issue by yvt** [Vector35/dwarf_import#14]
```
Traceback (most recent call last):
  File "/nix/store/j2g1lns927px777irnraxk63fh91kppy-binary-ninja-personal/opt/plugins/../python/binaryninja/plugin.py", line 227, in _default_is_valid
    return is_valid(view_obj)
  File ".../.binaryninja/repositories/official/plugins/Vector35_dwarf_import/__init__.py", line 60, in is_valid
    return raw and elf and ELFFile(bn.binaryview.BinaryReader(bv.file.raw)).has_dwarf_info()
  File ".../.binaryninja/python39/site-packages/elftools/elf/elffile.py", line 182, in has_dwarf_info
    return bool(self.get_section_by_name('.debug_info') or
  File ".../.binaryninja/python39/site-packages/elftools/elf/elffile.py", line 124, in get_section_by_name
    for i, sec in enumerate(self.iter_sections()):
  File ".../.binaryninja/python39/site-packages/elftools/elf/elffile.py", line 133, in iter_sections
    yield self.get_section(i)
  File ".../.binaryninja/python39/site-packages/elftools/elf/elffile.py", line 113, in get_section
    return self._make_section(section_header)
  File ".../.binaryninja/python39/site-packages/elftools/elf/elffile.py", line 569, in _make_section
    return ARMAttributesSection(section_header, name, self)
  File ".../.binaryninja/python39/site-packages/elftools/elf/sections.py", line 474, in __init__
    self.subsec_start = self.stream.tell()
AttributeError: 'BinaryReader' object has no attribute 'tell'
```

The error only occurs when an Arm ELF file is opened. It doesn't occur with x86.

## Systen information

 - NixOS Unstable (The problem can be reproduced on macOS, too)
 - Binary Ninja Version 2.4.2846 Personal
 - DWARF Import v1.0.4 (installed through "Manage Plugins")
 - pyelftools 0.27

**Comment by KyleMiles** [comment]
This is resolved in version 1.1.0.

**Comment by KyleMiles** [comment]
You'll need to be on the development branch to use the plugin, now, however... Until the next stable (presumably 3.0).

**Comment by Ethan-ks** [comment]
This is not fixed in version 1.1.1 (latest from master at time of writing)
Binary Ninja version: 2.5.3112-dev
File information: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.31, with debug_info, not stripped

I see the same error that yvt reported.

**Comment by KyleMiles** [comment]
Would you be able to provide the binary?

**Comment by Ethan-ks** [comment]
Unfortunately no, let me see if I can reproduce the behavior on a binary I can share, just a sec

**Comment by Ethan-ks** [comment]
Thanks for waiting -- here is a binary with which you can reproduce the behavior. 
[arm-unpack.tar.gz](https://github.com/Vector35/dwarf_import/files/7584901/arm-unpack.tar.gz)

**Comment by Green-Avocado** [comment]
I get the same error on some x86-64 ELFs with DWARF Import 1.1.1, Binary Ninja 3.0.336-dev Personal

**Comment by SWW13** [comment]
```patch
diff --git a/__init__.py b/__init__.py
index 4f7b8cc..b27921f 100644
--- a/__init__.py
+++ b/__init__.py
@@ -28,6 +28,12 @@ from .mapped_model import AnalysisSession
 from elftools.elf.elffile import ELFFile
 import os

+class BinaryReaderFixed(BinaryReader):
+    def __init__(self, *args, **kwargs) -> None:
+        super().__init__(*args, **kwargs)
+
+    def tell(self):
+        return self.offset

 class DWARF_loader(BackgroundTaskThread):
   def __init__(self, bv, debug_file=None):
@@ -89,7 +95,7 @@ def is_valid(bv):
       elf = True
     elif view.name == "Raw":
       raw = True
-  return raw and elf and ELFFile(BinaryReader(bv.file.raw)).has_dwarf_info()
+  return raw and elf and ELFFile(BinaryReaderFixed(bv.file.raw)).has_dwarf_info()


 PluginCommand.register("DWARF Import\\Load DWARF Symbols", "Load DWARF Symbols from the current file", load_symbols, is_valid)
 ```
