### ISSUE TITLE
Unable to run on 2.4.3105-dev: Attribute Error

### ISSUE THREAD

**Issue by SmoothHacker** [Vector35/dwarf_import#15]
Executing the dwarf_import plugin on version `2.4.3105-dev` leads to the following error `AttributeError: module 'binaryninja' has no attribute 'NamedTypeReference'. The full traceback is bellow.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\lagle\AppData\Local\Programs\Python\Python39\Lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\lagle\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 808, in run
    self.task.run()
  File "C:\Users\lagle\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\__init__.py", line 42, in run
    bridge.import_debug_info()
  File "C:\Users\lagle\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\bridge.py", line 316, in import_debug_info
    self.apply_all_types()
  File "C:\Users\lagle\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\bridge.py", line 328, in apply_all_types
    self._translate_type(ty)
  File "C:\Users\lagle\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\bridge.py", line 566, in _translate_type
    binja_type = self._construct_binja_type(ty)
  File "C:\Users\lagle\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\bridge.py", line 717, in _construct_binja_type
    binja_type = bn.Type.named_type(bn.NamedTypeReference(name=ty.name, type_id=self._generate_typeid(ty.name), type_class=ntrc))
AttributeError: module 'binaryninja' has no attribute 'NamedTypeReference'
```

**Comment by KyleMiles** [comment]
This is resolved in version 1.1.0.
