### ISSUE TITLE
Errors when parsing binary compiled with DWARFv5

### ISSUE THREAD

**Issue by Ninja3047** [Vector35/dwarf_import#16]
Sample Binary
[test.tar.gz](https://github.com/Vector35/dwarf_import/files/7943067/test.tar.gz)
Error:

During parsing:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 860, in run
    self.task.run()
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/__init__.py", line 37, in run
    analysis_session = AnalysisSession(binary_view = self.view, debug_file = self.debug_file)
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/mapped_model.py", line 65, in __init__
    m = AnalysisModel.from_dwarf(debug_source, self.debug_root, name=binary_name, logger=logger)
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/model/analysis_model.py", line 271, in from_dwarf
    import_ELF_DWARF_into_model(elf_file, model, debug_root=debug_root, logger=logger)
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 1486, in import_ELF_DWARF_into_model
    dwarf_db = DWARFDB(elf_file, debug_root)
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 263, in __init__
    self._pri = DWARFData(elf_file, debug_root)
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 182, in __init__
    self._index()
  File "/Users/kyle/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 185, in _index
    for cu in self._dwarf_info.iter_CUs():
  File "/Users/kyle/Library/Python/3.8/lib/python/site-packages/elftools/dwarf/dwarfinfo.py", line 353, in _parse_CUs_iter
    cu = self._cached_CU_at_offset(offset)
  File "/Users/kyle/Library/Python/3.8/lib/python/site-packages/elftools/dwarf/dwarfinfo.py", line 383, in _cached_CU_at_offset
    cu = self._parse_CU_at_offset(offset)
  File "/Users/kyle/Library/Python/3.8/lib/python/site-packages/elftools/dwarf/dwarfinfo.py", line 417, in _parse_CU_at_offset
    cu_structs = DWARFStructs(
  File "/Users/kyle/Library/Python/3.8/lib/python/site-packages/elftools/dwarf/structs.py", line 92, in __init__
    assert address_size == 8 or address_size == 4
AssertionError
```

After parsing (while the UI checks if the callback is valid or not):
```
Traceback (most recent call last):
  File "/home/user/binaryninja/plugins/../python/binaryninja/plugin.py", line 225, in _default_is_valid
    return is_valid(view_obj)
  File "/home/user/.binaryninja/repositories/official/plugins/Vector35_dwarf_import/__init__.py", line 81, in is_valid
    for view in bv.file.raw.available_view_types:
AttributeError: 'NoneType' object has no attribute 'available_view_types'
```

**Comment by Ninja3047** [comment]
Binary compiled with `gcc -g -gdwarf-5 test.c -o test` on a recent gcc

**Comment by KyleMiles** [comment]
I'm not sure what's happening here.  The BV getting cannibalized during parsing is a known issue, causing the repeated errors in the very long log you shared (I've removed those to make your report better).  The core issue at the top, being in elftools, is wontfix/upstream.

**Comment by KyleMiles** [comment]
I'll also note that we're reimplementing this in the core, and this will hopefully be resolved in that rewrite.

**Comment by psifertex** [comment]
https://github.com/eliben/pyelftools/issues/391
is the upstream issue here
