### ISSUE TITLE
AssertionError on a global variable with no type attribute

### ISSUE THREAD

**Issue by SmoothHacker** [Vector35/dwarf_import#19]
I was trying to apply DWARF info for the attached binary and the plugin suffered an assertion failure when importing a global variable. It was trying to import a `DW_TAG_variable` die with no `DW_AT_type` attribute. In the source for this binary, the variable that it was trying to import is an `extern const char *`.

Here's the output of llvm-dwarfdump. Based on added logging in the plugin, the assertion error happened when it was trying to inspect the `DW_TAG_variable` at 0x25.
```sh
0x0000001d:   DW_TAG_variable
                DW_AT_name  ("buildstring")
                DW_AT_decl_file ("/tmp/Darkplaces.build.linux64/build-obj/release/darkplaces-dedicated/../../../builddate.c")
                DW_AT_decl_line (4)
                DW_AT_decl_column   (0x14)
                DW_AT_external  (true)
                DW_AT_declaration   (true)

0x00000025:   DW_TAG_variable
                DW_AT_specification (0x0000001d "buildstring")
                DW_AT_decl_line (5)
                DW_AT_decl_column   (0x0d)
                DW_AT_location  (DW_OP_addr 0x4d0490)
```

Traceback for the plugin:
```Python3
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 928, in run
    self.task.run()
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/__init__.py", line 41, in run
    analysis_session = AnalysisSession(binary_view = self.view, debug_file = self.debug_file)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/mapped_model.py", line 67, in __init__
    m = AnalysisModel.from_dwarf(debug_source, self.debug_root, name=binary_name, logger=logger)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/model/analysis_model.py", line 297, in from_dwarf
    import_ELF_DWARF_into_model(elf_file, model, debug_root=debug_root, logger=logger)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 1468, in import_ELF_DWARF_into_model
    importer.import_debug_info()
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 671, in import_debug_info
    self.import_compilation_unit(cu_die)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 689, in import_compilation_unit
    self.import_global_variable(child)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/io/dwarf_import.py", line 765, in import_global_variable
    assert(type_die)
AssertionError
Traceback (most recent call last):
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/plugin.py", line 229, in _default_is_valid
    return is_valid(view_obj)
  File "/Users/scott/Library/Application Support/Binary Ninja/plugins/dwarf_import/__init__.py", line 92, in is_valid
    reader = BinaryReader(bv.file.raw)
  File "/Applications/Binary Ninja.app/Contents/MacOS/plugins/../../Resources/python/binaryninja/binaryview.py", line 7908, in __init__
    _handle = core.BNCreateBinaryReader(view.handle)
AttributeError: 'NoneType' object has no attribute 'handle'
```

Another issue I noticed is that when the plugin failed, `bv.file.raw` becomes a `None` type not a `BinaryView` as intended. The AttributeError in the provided traceback shows this.

Binary in question: [xonotic-linux64-dedicated.zip](https://github.com/Vector35/dwarf_import/files/9821458/xonotic-linux64-dedicated.zip)

**Comment by KyleMiles** [comment]
Please try this in 3.5.4378-dev: https://github.com/Vector35/binaryninja-api/issues/3206#issuecomment-1629342753.
