### ISSUE TITLE
AttributeError: 'BinjaBridge' object has no attribute '_create_global_component'

### ISSUE THREAD

**Issue by yrp604** [Vector35/dwarf_import#7]
Windows 10 Personal 2480-dev

Tools -> DWARF Import gives the following error

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python39\Lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\x\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 731, in run
    self.task.run()
  File "C:\Users\x\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\__init__.py", line 42, in run
    bridge.import_debug_info()
  File "C:\Users\x\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_dwarf_import\bridge.py", line 304, in import_debug_info
    self._module.add_component(self._create_global_component())
AttributeError: 'BinjaBridge' object has no attribute '_create_global_component'
```

**Comment by yrp604** [comment]
Dupe of #5
